import { useEffect, useMemo, useState, type ReactNode, type CSSProperties } from 'react';
import { motion } from 'framer-motion';
import {
  Accessibility, ArrowLeft, Bell, Check, ChevronDown, CircleHelp, Cpu, Download,
  Keyboard, LockKeyhole, MessageSquare, Mic2, Moon, Palette, Settings2, ShieldCheck,
  Sparkles, Sun, Trash2, Volume2, Waves, Zap,
} from 'lucide-react';
import { useLocation } from 'wouter';
import {
  clearPreferenceStore, DEFAULT_SETTINGS, loadSingularitySettings, saveSingularitySettings,
  type Accent, type SettingsCategory, type SingularitySettings, type Theme,
} from '@/lib/singularitySettings';
import { clearChatHistoryStorage } from '@/lib/singularityChatHistory';

const CATEGORIES: Array<{ id: SettingsCategory; label: string; description: string; icon: typeof Settings2 }> = [
  { id: 'general', label: 'General', description: 'Workspace defaults', icon: Settings2 },
  { id: 'appearance', label: 'Appearance', description: 'Your visual field', icon: Palette },
  { id: 'chat', label: 'Chat', description: 'Conversation behavior', icon: MessageSquare },
  { id: 'voice', label: 'Voice', description: 'Speech and microphone', icon: Mic2 },
  { id: 'ai', label: 'AI', description: 'Reasoning preferences', icon: Sparkles },
  { id: 'notifications', label: 'Notifications', description: 'Signals and shortcuts', icon: Bell },
  { id: 'privacy', label: 'Privacy', description: 'Local data controls', icon: LockKeyhole },
  { id: 'accessibility', label: 'Accessibility', description: 'Make it yours', icon: Accessibility },
  { id: 'about', label: 'About', description: 'System information', icon: CircleHelp },
];

const inputClass = 'mt-2 w-full rounded-xl border border-white/[0.1] bg-black/[0.16] px-3 py-2.5 text-[12px] text-white/85 outline-none transition-colors focus:border-[var(--settings-accent)]';
const options = (items: string[]) => items.map(item => <option key={item} value={item}>{item}</option>);

function Field({ label, hint, children, testId }: { label: string; hint?: string; children: ReactNode; testId?: string }) {
  return <div data-testid={testId} className="py-3.5">
    <div className="flex items-start justify-between gap-4"><label className="text-[12px] font-medium text-white/80">{label}</label>{hint && <span className="max-w-[16rem] text-right text-[10px] leading-relaxed text-white/32">{hint}</span>}</div>
    {children}
  </div>;
}

function SelectField({ label, value, onChange, items, hint, testId }: { label: string; value: string; onChange: (value: string) => void; items: string[]; hint?: string; testId: string }) {
  return <Field label={label} hint={hint} testId={testId}><select data-testid={`select-${testId}`} className={inputClass} value={value} onChange={event => onChange(event.target.value)}>{options(items)}</select></Field>;
}

function Toggle({ label, description, checked, onChange, testId }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void; testId: string }) {
  return <button type="button" data-testid={testId} role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className="flex w-full items-center justify-between gap-5 rounded-xl px-2 py-3 text-left transition-colors hover:bg-white/[0.035] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--settings-accent)]">
    <span><span className="block text-[12px] font-medium text-white/78">{label}</span><span className="mt-0.5 block text-[10px] leading-relaxed text-white/35">{description}</span></span>
    <span className={`relative h-5 w-9 flex-shrink-0 rounded-full border transition-colors ${checked ? 'border-[var(--settings-accent)] bg-[var(--settings-accent)]' : 'border-white/15 bg-white/[0.06]'}`}><span className={`absolute top-0.5 h-3.5 w-3.5 rounded-full bg-white transition-transform ${checked ? 'translate-x-[18px]' : 'translate-x-0.5'}`} /></span>
  </button>;
}

function Segmented({ label, value, items, onChange, testId }: { label: string; value: string; items: Array<{ value: string; label: string; icon?: ReactNode }>; onChange: (value: string) => void; testId: string }) {
  return <Field label={label}><div data-testid={testId} className="mt-2 grid grid-cols-2 gap-1 rounded-xl border border-white/[0.09] bg-black/[0.14] p-1 sm:grid-cols-4">{items.map(item => <button key={item.value} type="button" data-testid={`${testId}-${item.value}`} onClick={() => onChange(item.value)} className={`flex items-center justify-center gap-1.5 rounded-lg px-2 py-2 text-[10px] transition-colors ${value === item.value ? 'bg-[var(--settings-accent)] text-white shadow-lg' : 'text-white/42 hover:bg-white/[0.05] hover:text-white/75'}`}>{item.icon}{item.label}</button>)}</div></Field>;
}

function Card({ title, eyebrow, icon, children, testId }: { title: string; eyebrow: string; icon: ReactNode; children: ReactNode; testId: string }) {
  return <section data-testid={testId} className="overflow-hidden rounded-2xl border border-white/[0.09] bg-white/[0.035] shadow-[0_18px_45px_rgba(0,0,0,0.14)]"><div className="flex items-start gap-3 border-b border-white/[0.07] px-5 py-4"><span className="mt-0.5 flex h-8 w-8 items-center justify-center rounded-xl border border-[var(--settings-accent)]/30 bg-[var(--settings-accent)]/10 text-[var(--settings-accent)]">{icon}</span><div><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-[var(--settings-accent)]/75">{eyebrow}</p><h2 className="mt-1 text-[15px] font-medium tracking-[-0.02em] text-white/90">{title}</h2></div></div><div className="divide-y divide-white/[0.06] px-5">{children}</div></section>;
}

function SettingsContent({ category, settings, update }: { category: SettingsCategory; settings: SingularitySettings; update: <K extends keyof SingularitySettings>(section: K, key: keyof SingularitySettings[K], value: unknown) => void }) {
  const appearance = settings.appearance, chat = settings.chat, voice = settings.voice, ai = settings.ai;
  if (category === 'general') return <div className="space-y-4"><Card title="Workspace defaults" eyebrow="General" icon={<Settings2 size={15} />} testId="settings-card-general"><SelectField label="Interface language" value={settings.general.language} onChange={v => update('general', 'language', v)} items={['English', 'Spanish', 'French', 'German', 'Japanese']} testId="interface-language" /><SelectField label="Time display" value={settings.general.timezone} onChange={v => update('general', 'timezone', v)} items={['Local time', 'UTC', '24-hour local time']} testId="time-display" /><div className="py-4 text-[11px] leading-relaxed text-white/38">These preferences stay in this browser and never alter the chat transport.</div></Card></div>;
  if (category === 'appearance') return <div className="space-y-4"><Card title="Visual field" eyebrow="Appearance" icon={<Palette size={15} />} testId="settings-card-appearance"><Segmented label="Theme" value={appearance.theme} onChange={v => update('appearance', 'theme', v)} testId="theme-control" items={[{ value: 'light', label: 'Light', icon: <Sun size={12} /> }, { value: 'dark', label: 'Dark', icon: <Moon size={12} /> }, { value: 'system', label: 'System' }]} /><Field label="Accent color" hint="Preview applies instantly"><div className="mt-3 flex flex-wrap gap-2" data-testid="accent-color-control">{(['violet', 'cyan', 'amber', 'rose'] as Accent[]).map(accent => <button type="button" key={accent} data-testid={`accent-${accent}`} aria-label={`${accent} accent`} onClick={() => update('appearance', 'accent', accent)} className={`h-8 w-8 rounded-full border-2 transition-transform ${appearance.accent === accent ? 'scale-110 border-white' : 'border-transparent'}`} style={{ background: `var(--accent-${accent})` }} />)}</div></Field><SelectField label="Density" value={appearance.density} onChange={v => update('appearance', 'density', v)} items={['comfortable', 'compact', 'spacious']} testId="density" /><SelectField label="Message width" value={appearance.messageWidth} onChange={v => update('appearance', 'messageWidth', v)} items={['narrow', 'standard', 'wide']} testId="message-width" /><SelectField label="Font size" value={appearance.fontSize} onChange={v => update('appearance', 'fontSize', v)} items={['small', 'medium', 'large']} testId="font-size" /></Card></div>;
  if (category === 'chat') return <div className="space-y-4"><Card title="Conversation behavior" eyebrow="Chat" icon={<MessageSquare size={15} />} testId="settings-card-chat"><SelectField label="Streaming speed" value={chat.streamingSpeed} onChange={v => update('chat', 'streamingSpeed', v)} items={['steady', 'fast', 'instant']} testId="streaming-speed" /><Toggle label="Auto-scroll" description="Follow new responses while a conversation is active." checked={chat.autoScroll} onChange={v => update('chat', 'autoScroll', v)} testId="toggle-auto-scroll" /><Toggle label="Markdown rendering" description="Format headings, lists, links, and emphasis." checked={chat.markdown} onChange={v => update('chat', 'markdown', v)} testId="toggle-markdown" /><Toggle label="Wrap code blocks" description="Keep long lines inside the message column." checked={chat.codeWrapping} onChange={v => update('chat', 'codeWrapping', v)} testId="toggle-code-wrapping" /><Toggle label="Math rendering" description="Render LaTeX notation as readable equations." checked={chat.math} onChange={v => update('chat', 'math', v)} testId="toggle-math" /><Toggle label="Message animations" description="Use subtle entrance motion for new messages." checked={chat.messageAnimations} onChange={v => update('chat', 'messageAnimations', v)} testId="toggle-message-animations" /><Toggle label="Typing animation" description="Reveal generated text progressively." checked={chat.typingAnimation} onChange={v => update('chat', 'typingAnimation', v)} testId="toggle-typing-animation" /><Toggle label="Timestamps" description="Show message time beneath each response." checked={chat.timestamps} onChange={v => update('chat', 'timestamps', v)} testId="toggle-timestamps" /></Card></div>;
  if (category === 'voice') return <div className="space-y-4"><Card title="Audio environment" eyebrow="Voice" icon={<Volume2 size={15} />} testId="settings-card-voice"><Toggle label="Voice output" description="Allow Singularity to speak responses." checked={voice.enabled} onChange={v => update('voice', 'enabled', v)} testId="toggle-voice-output" /><SelectField label="Voice" value={voice.voice} onChange={v => update('voice', 'voice', v)} items={['Nova · Neural', 'Sage · Neural', 'Orbit · Neural']} testId="voice-choice" /><Field label="Speaking speed" hint={`${voice.rate.toFixed(1)}×`}><input data-testid="range-speaking-speed" type="range" min="0.6" max="1.6" step="0.1" value={voice.rate} onChange={e => update('voice', 'rate', Number(e.target.value))} className="mt-4 w-full accent-[var(--settings-accent)]" /></Field><Toggle label="Autoplay responses" description="Start voice playback when an answer completes." checked={voice.autoplay} onChange={v => update('voice', 'autoplay', v)} testId="toggle-autoplay" /><Field label="Microphone sensitivity" hint={`${voice.sensitivity}%`}><input data-testid="range-microphone-sensitivity" type="range" min="0" max="100" value={voice.sensitivity} onChange={e => update('voice', 'sensitivity', Number(e.target.value))} className="mt-4 w-full accent-[var(--settings-accent)]" /></Field><Toggle label="Noise suppression" description="Reduce consistent room noise before capture." checked={voice.noiseSuppression} onChange={v => update('voice', 'noiseSuppression', v)} testId="toggle-noise-suppression" /><Toggle label="Echo cancellation" description="Prevent speaker audio from returning to the microphone." checked={voice.echoCancellation} onChange={v => update('voice', 'echoCancellation', v)} testId="toggle-echo-cancellation" /></Card></div>;
  if (category === 'ai') return <div className="space-y-4"><Card title="Reasoning profile" eyebrow="AI" icon={<Cpu size={15} />} testId="settings-card-ai"><SelectField label="Model" value={ai.model} onChange={v => update('ai', 'model', v)} items={['GPT-OSS-120B', 'DeepSeek R1', 'Singularity Auto']} testId="ai-model" /><SelectField label="Reasoning level" value={ai.reasoning} onChange={v => update('ai', 'reasoning', v)} items={['focused', 'balanced', 'deep']} testId="reasoning-level" /><SelectField label="Response length" value={ai.responseLength} onChange={v => update('ai', 'responseLength', v)} items={['concise', 'balanced', 'detailed']} testId="response-length" /><SelectField label="Writing style" value={ai.writingStyle} onChange={v => update('ai', 'writingStyle', v)} items={['precise', 'conversational', 'academic']} testId="writing-style" /><SelectField label="Creativity" value={ai.creativity} onChange={v => update('ai', 'creativity', v)} items={['low', 'balanced', 'high']} testId="creativity" /><Field label="Temperature" hint={ai.temperature.toFixed(1)}><input data-testid="range-temperature" type="range" min="0" max="1.4" step="0.1" value={ai.temperature} onChange={e => update('ai', 'temperature', Number(e.target.value))} className="mt-4 w-full accent-[var(--settings-accent)]" /></Field><SelectField label="Response language" value={ai.language} onChange={v => update('ai', 'language', v)} items={['English', 'Hindi', 'Japanese', 'Spanish', 'French']} testId="ai-language" /><Field label="Custom instructions" hint="Optional"><textarea data-testid="textarea-custom-instructions" value={ai.customInstructions} onChange={e => update('ai', 'customInstructions', e.target.value)} rows={4} maxLength={1000} placeholder="Tell Singularity how to work with you…" className={`${inputClass} resize-y`} /></Field></Card></div>;
  if (category === 'notifications') return <div className="space-y-4"><Card title="Productivity signals" eyebrow="Notifications" icon={<Keyboard size={15} />} testId="settings-card-notifications"><Toggle label="Keyboard shortcuts" description="Enable command shortcuts such as Cmd/Ctrl + K." checked={settings.notifications.keyboardShortcuts} onChange={v => update('notifications', 'keyboardShortcuts', v)} testId="toggle-keyboard-shortcuts" /><Toggle label="Autofocus composer" description="Place the cursor in the composer when chat opens." checked={settings.notifications.autofocus} onChange={v => update('notifications', 'autofocus', v)} testId="toggle-autofocus-composer" /><Toggle label="Enter to send" description="Send a message with Enter." checked={settings.notifications.enterToSend} onChange={v => update('notifications', 'enterToSend', v)} testId="toggle-enter-to-send" /><Toggle label="Shift + Enter for newline" description="Add a line break without sending." checked={settings.notifications.shiftEnterNewline} onChange={v => update('notifications', 'shiftEnterNewline', v)} testId="toggle-shift-enter" /><Toggle label="Desktop notifications" description="Ask this browser before showing background alerts." checked={settings.notifications.desktop} onChange={v => update('notifications', 'desktop', v)} testId="toggle-desktop-notifications" /></Card></div>;
  if (category === 'accessibility') return <div className="space-y-4"><Card title="Comfort and access" eyebrow="Accessibility" icon={<Accessibility size={15} />} testId="settings-card-accessibility"><Toggle label="Reduced motion" description="Minimize transitions and animated feedback." checked={settings.accessibility.reducedMotion} onChange={v => update('accessibility', 'reducedMotion', v)} testId="toggle-reduced-motion" /><Toggle label="High contrast" description="Increase separation between text, controls, and surfaces." checked={settings.accessibility.highContrast} onChange={v => update('accessibility', 'highContrast', v)} testId="toggle-high-contrast" /><Toggle label="Large fonts" description="Increase the reading scale across this settings surface." checked={settings.accessibility.largeFonts} onChange={v => update('accessibility', 'largeFonts', v)} testId="toggle-large-fonts" /><Toggle label="Keyboard navigation" description="Keep focus states prominent and predictable." checked={settings.accessibility.keyboardNavigation} onChange={v => update('accessibility', 'keyboardNavigation', v)} testId="toggle-keyboard-navigation" /><Toggle label="Screen reader descriptions" description="Prefer verbose labels for dynamic controls." checked={settings.accessibility.screenReader} onChange={v => update('accessibility', 'screenReader', v)} testId="toggle-screen-reader" /></Card></div>;
  if (category === 'privacy') return <PrivacyCard settings={settings} />;
  return <AboutCard />;
}

function PrivacyCard({ settings }: { settings: SingularitySettings }) {
  const [confirm, setConfirm] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  const perform = async (action: string) => {
    try {
      if (action === 'export') {
        const payload = JSON.stringify({ exportedAt: new Date().toISOString(), preferences: settings }, null, 2);
        const url = URL.createObjectURL(new Blob([payload], { type: 'application/json' }));
        const link = document.createElement('a'); link.href = url; link.download = 'singularity-local-preferences.json'; link.click(); URL.revokeObjectURL(url);
        setNotice('Preferences exported to this device.');
      } else if (action === 'preferences') { clearPreferenceStore(); setNotice('Preference store cleared. Reload to restore defaults.'); }
      else if (action === 'cache') { window.localStorage.clear(); setNotice('Browser-local cache cleared. Chat data was not sent anywhere.'); }
      else if (action === 'history') {
        await clearChatHistoryStorage();
        setNotice('Local chat history cleared from this browser.');
      }
      else if (action === 'reset') {
        await clearChatHistoryStorage();
        window.localStorage.clear();
        setNotice('Application-local data reset.');
      }
    } catch { setNotice('The browser blocked this local action. No remote data was changed.'); }
    setConfirm(null);
  };
  const actions = [{ id: 'history', label: 'Clear chat history', description: 'Remove conversations stored in this browser only.', danger: true }, { id: 'cache', label: 'Clear local cache', description: 'Remove browser-local application caches.', danger: true }, { id: 'export', label: 'Export preferences', description: 'Download a JSON copy of your current preferences.', danger: false }, { id: 'preferences', label: 'Delete preferences', description: 'Return this preference store to its defaults.', danger: true }, { id: 'reset', label: 'Reset application', description: 'Clear all local storage for this application.', danger: true }];
  return <div className="space-y-4"><Card title="Local boundaries" eyebrow="Privacy" icon={<ShieldCheck size={15} />} testId="settings-card-privacy"><p className="py-4 text-[11px] leading-relaxed text-white/40">Singularity settings are stored locally in this browser. These controls do not call an API and cannot delete data from an account or server.</p>{actions.map(action => <div key={action.id} className="flex items-center justify-between gap-4 py-4"><div><p className="text-[12px] font-medium text-white/76">{action.label}</p><p className="mt-1 text-[10px] text-white/35">{action.description}</p></div><button type="button" data-testid={`privacy-${action.id}`} onClick={() => action.danger ? setConfirm(action.id) : perform(action.id)} className={`flex-shrink-0 rounded-lg border px-2.5 py-2 text-[10px] transition-colors ${action.danger ? 'border-red-300/20 text-red-200/75 hover:bg-red-400/10' : 'border-[var(--settings-accent)]/25 text-[var(--settings-accent)] hover:bg-[var(--settings-accent)]/10'}`}>{action.id === 'export' ? <Download size={12} /> : <Trash2 size={12} />}</button></div>)}{notice && <p data-testid="privacy-notice" role="status" className="border-t border-white/[0.07] py-3 text-[10px] text-emerald-200/75">{notice}</p>}</Card>{confirm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div role="alertdialog" aria-modal="true" className="w-full max-w-sm rounded-2xl border border-white/[0.12] bg-[#171720] p-5 shadow-2xl"><h2 className="text-[15px] font-medium text-white/90">Confirm local action</h2><p className="mt-2 text-[12px] leading-relaxed text-white/45">This only changes data in this browser. It cannot be undone.</p><div className="mt-5 flex justify-end gap-2"><button type="button" data-testid="privacy-cancel" onClick={() => setConfirm(null)} className="rounded-lg px-3 py-2 text-[11px] text-white/50 hover:bg-white/[0.06]">Cancel</button><button type="button" data-testid="privacy-confirm" onClick={() => perform(confirm)} className="rounded-lg bg-red-400/15 px-3 py-2 text-[11px] text-red-100 hover:bg-red-400/25">Confirm</button></div></div></div>}</div>;
}

function AboutCard() {
  const rows = [['Version', '0.8.4 · Singularity'], ['Current model', 'GPT-OSS-120B'], ['Frontend', 'React 18 · Vite · TypeScript'], ['Runtime', 'Framer Motion · Tailwind CSS'], ['License', 'Proprietary workspace license'], ['Release notes', 'Local personalization hub with defensive preference storage']];
  return <div className="space-y-4"><Card title="The instrument panel" eyebrow="About" icon={<Sparkles size={15} />} testId="settings-card-about"><div className="grid gap-0 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} data-testid={`about-${label.toLowerCase().replace(' ', '-')}`} className="border-b border-white/[0.06] py-4 sm:odd:mr-4 sm:even:ml-4"><p className="text-[9px] uppercase tracking-[0.16em] text-white/28">{label}</p><p className="mt-1.5 text-[12px] leading-relaxed text-white/72">{value}</p></div>)}</div></Card></div>;
}

export default function SingularitySettingsPage({ onBack }: { onBack?: () => void }) {
  const [, setLocation] = useLocation();
  const [settings, setSettings] = useState<SingularitySettings>(() => loadSingularitySettings());
  const [category, setCategory] = useState<SettingsCategory>('general');
  const theme: Theme = settings.appearance.theme;
  const resolvedTheme = theme === 'system' ? (typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark') : theme;
  const accent = { violet: '#a78bfa', cyan: '#67e8f9', amber: '#fbbf24', rose: '#fb7185' }[settings.appearance.accent];
  useEffect(() => saveSingularitySettings(settings), [settings]);
  const update = <K extends keyof SingularitySettings>(section: K, key: keyof SingularitySettings[K], value: unknown) => setSettings(previous => ({ ...previous, [section]: { ...(previous[section] as object), [key]: value } } as SingularitySettings));
  const selected = useMemo(() => CATEGORIES.find(item => item.id === category) ?? CATEGORIES[0], [category]);
  return <div data-testid="settings-page" className={`settings-surface ${resolvedTheme === 'light' ? 'settings-light' : ''} ${settings.accessibility.highContrast ? 'settings-high-contrast' : ''} ${settings.accessibility.largeFonts ? 'settings-large-fonts' : ''}`} style={{ '--settings-accent': accent, '--accent-violet': '#a78bfa', '--accent-cyan': '#67e8f9', '--accent-amber': '#fbbf24', '--accent-rose': '#fb7185' } as CSSProperties}>
    <header className="settings-topbar"><button type="button" data-testid="button-return-chat" onClick={() => onBack ? onBack() : setLocation('/chat')} className="settings-back"><ArrowLeft size={15} /> <span>Return to chat</span></button><div className="settings-save"><span className="hidden sm:inline">Saved locally</span><Check size={13} /></div></header>
    <div className="settings-layout"><aside className="settings-nav"><div className="settings-brand"><div className="settings-mark"><Waves size={16} /></div><div><p className="settings-kicker">Singularity</p><h1>Settings</h1></div></div><label className="settings-mobile-select">Category<select data-testid="select-settings-category" value={category} onChange={e => setCategory(e.target.value as SettingsCategory)}>{CATEGORIES.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select><ChevronDown size={14} /></label><nav className="settings-category-list" aria-label="Settings categories">{CATEGORIES.map(item => { const Icon = item.icon; return <button type="button" key={item.id} data-testid={`nav-settings-${item.id}`} onClick={() => setCategory(item.id)} className={`settings-category ${category === item.id ? 'is-active' : ''}`}><Icon size={15} /><span><strong>{item.label}</strong><small>{item.description}</small></span>{category === item.id && <span className="settings-active-dot" />}</button>; })}</nav><div className="settings-nav-foot"><Zap size={13} /> Preferences are browser-local</div></aside><main className="settings-content"><motion.div key={category} initial={{ opacity: 0, y: 7 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: settings.accessibility.reducedMotion ? 0 : 0.2 }}><div className="settings-heading"><div><p className="settings-kicker">Control center / {selected.label}</p><h2>{selected.label}</h2><p>{selected.description}. Adjust the environment around your work without leaving the conversation behind.</p></div><div className="settings-orbit" aria-hidden="true"><span /><span /><span /></div></div><SettingsContent category={category} settings={settings} update={update} /></motion.div></main></div>
  </div>;
}