import { Router } from "express";

const router = Router();
const VISUAL_REFERENCE_CACHE_TTL_MS = 15 * 60_000;
const visualReferenceCache = new Map<string, {
  expiresAt: number;
  references: VisualReference[];
}>();

interface VisualReference {
  id: string;
  title: string;
  caption: string;
  imageUrl: string;
  sourceUrl: string;
  source: string;
  alt: string;
  confidence: number;
  sourceTier: 1 | 2 | 3;
  width: number;
  height: number;
}

type VisualCategory =
  | "science"
  | "mathematics"
  | "physics"
  | "astronomy"
  | "biology"
  | "chemistry"
  | "geography"
  | "architecture"
  | "engineering"
  | "people"
  | "places"
  | "history"
  | "animals"
  | "plants"
  | "hardware"
  | "technology"
  | "concept"
  | "other";

const HIGH_VALUE_RULES: Array<{ category: VisualCategory; pattern: RegExp }> = [
  { category: "mathematics", pattern: /\b(mathematics?|geometry|trigonometry|calculus|algebra|graph theory|topology|probability|statistics|equation|theorem|matrix)\b/i },
  { category: "physics", pattern: /\b(physics|quantum|relativity|mechanics|thermodynamics|electromagnetism|particle|wave|photon|electron|feynman)\b/i },
  { category: "chemistry", pattern: /\b(chemistry|chemical|molecule(?:s)?|atom(?:s)?|reaction|periodic table|organic chemistry|catalyst)\b/i },
  { category: "biology", pattern: /\b(biology|cell(?:s)?|gene(?:s)?|dna|rna|evolution|anatom(?:y|ies)|medical|medicine|microscope|fossil(?:s)?|neuron|protein)\b/i },
  { category: "astronomy", pattern: /\b(astronomy|cosmology|planet(?:s)?|galax(?:y|ies)|nebula(?:e|s)?|black holes?|star(?:s)?|moon(?:s)?|mars|solar system|space|telescope)\b/i },
  { category: "geography", pattern: /\b(geography|map|mountain|river|island|continent|ocean|climate)\b/i },
  { category: "architecture", pattern: /\b(architecture|building|architectural|structure|landmark|monument|temple|cathedral|skyscraper)\b/i },
  { category: "engineering", pattern: /\b(engineering|bridge|turbine|engine|machine|mechanical|civil engineering|technical drawing|schematic)\b/i },
  { category: "people", pattern: /\b(portrait|famous|person|people|scientist|artist|author|president|leader|einstein|newton|curie)\b/i },
  { category: "places", pattern: /\b(city|country|travel|place|famous place|destination)\b/i },
  { category: "history", pattern: /\b(history|historical|ancient|civilization|war|revolution|timeline|empire|archaeology)\b/i },
  { category: "animals", pattern: /\b(animal|species|bird|whale|dinosaur|cat|dog|insect|mammal|reptile|amphibian)\b/i },
  { category: "plants", pattern: /\b(plant|plants|botany|flower|tree|leaf|fungus|mushroom|photosynthesis)\b/i },
  { category: "hardware", pattern: /\b(hardware|circuit|processor|chip|motherboard|camera|device|phone|computer|robot)\b/i },
  { category: "technology", pattern: /\b(technology|robotics|technical|computer|machine learning)\b/i },
  { category: "concept", pattern: /\b(concept|how it works|process|system|theory|model|visualization)\b/i },
];

const LOW_VALUE_PATTERN = /\b(code|coding|programming|programmer|debug|debugging|typescript|javascript|python|java|api|sql|essay|translation|translate|poetry|poem|philosophy|personal advice|legal|contract|email|memo|rewrite|story|storytelling|opinion|conversation)\b/i;
const EXPLICIT_VISUAL_PATTERN = /\b(show|see|visual|image|images|picture|pictures|photo|photos|diagram|diagrams|map|illustration|illustrations|visuali[sz]e|look like)\b/i;
const REJECT_IMAGE_PATTERN = /\b(meme|watermark|watermarked|clickbait|screenshot|logo|poster|collage|ai[- ]?generated|generated by|pinterest|blog|thumbnail|low[- ]?res)\b/i;

function classifyVisualNeed(userQuery: string, response: string): {
  enabled: boolean;
  explicit: boolean;
  category: VisualCategory;
  confidence: number;
} {
  const text = `${userQuery}\n${response.slice(0, 1800)}`;
  const explicit = EXPLICIT_VISUAL_PATTERN.test(userQuery);
  const match = HIGH_VALUE_RULES.find(rule => rule.pattern.test(text));
  if (LOW_VALUE_PATTERN.test(userQuery) && !explicit) {
    return { enabled: false, explicit, category: "other", confidence: 0 };
  }
  const confidence = explicit ? 98 : match ? 88 + (match.pattern.test(userQuery) ? 6 : 0) : 0;
  return {
    enabled: confidence >= 80,
    explicit,
    category: match?.category ?? "other",
    confidence,
  };
}

function buildEducationalQuery(userQuery: string, response: string, category: VisualCategory): string {
  const subject = userQuery
    .replace(/^(please|can you|could you|tell me|explain|what is|what are|how does|how do|how)\s+/i, "")
    .replace(/[?.!]+$/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120);

  if (/\bblack holes?\b/i.test(userQuery)) {
    return "black hole event horizon accretion disk visualization";
  }
  if (/\bquantum field theor(?:y|ies)\b/i.test(userQuery)) {
    return "quantum field theory Feynman diagram quantum vacuum visualization";
  }
  if (/\b(dna|deoxyribonucleic acid)\b/i.test(userQuery)) {
    return "DNA double helix molecular structure scientific visualization";
  }
  if (/\bphotosynthesis\b/i.test(userQuery)) {
    return "photosynthesis chloroplast light reaction scientific diagram";
  }
  if (/\b(planet|galaxy|nebula|star|moon|mars|solar system)\b/i.test(userQuery)) {
    return `${subject} astronomy scientific visualization`.slice(0, 190);
  }

  const suffix: Record<VisualCategory, string> = {
    science: "scientific diagram visualization",
    mathematics: "mathematical diagram visualization",
    physics: "physics diagram scientific visualization",
    astronomy: "astronomy scientific visualization",
    biology: "biological scientific illustration",
    chemistry: "chemistry molecular diagram",
    geography: "geographic map reference",
    architecture: "architectural reference photograph",
    engineering: "engineering technical diagram",
    people: "portrait historical photograph",
    places: "place reference photograph",
    history: "historical photograph timeline artifact",
    animals: "natural history photograph scientific illustration",
    plants: "botanical scientific photograph",
    hardware: "hardware technical photograph diagram",
    technology: "technical diagram engineering visualization",
    concept: "educational visual reference",
    other: "educational visual reference",
  };

  const responseHint = response
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, " ")
    .split(/\s+/)
    .filter(token => token.length > 3)
    .slice(0, 3)
    .join(" ");
  return `${subject || responseHint || "educational topic"} ${suffix[category]}`.slice(0, 190);
}

function captionFor(query: string, title: string, category: VisualCategory): string {
  const framing: Record<VisualCategory, string> = {
    science: "This reference makes the scientific structure or process easier to inspect.",
    mathematics: "This reference makes the mathematical structure or relationship easier to inspect.",
    physics: "This reference clarifies the physical process or interaction discussed.",
    astronomy: "This reference anchors the explanation in an observable astronomical structure.",
    biology: "This reference highlights the biological structure or process discussed.",
    chemistry: "This reference makes the molecular structure or reaction easier to inspect.",
    geography: "This reference gives the subject useful spatial context.",
    architecture: "This reference makes the structure and design easier to examine.",
    engineering: "This reference clarifies the system's physical or mechanical structure.",
    people: "This reference anchors the subject in a recognizable historical or human context.",
    places: "This reference gives the subject useful spatial context.",
    history: "This reference connects the explanation to a concrete historical record or artifact.",
    animals: "This reference highlights the subject's visible form and distinguishing features.",
    plants: "This reference highlights the subject's visible form and distinguishing features.",
    hardware: "This reference makes the device's physical structure and design easier to compare.",
    technology: "This reference clarifies the system's physical structure or engineering context.",
    concept: "This reference provides concrete visual context for the concept.",
    other: "This reference provides concrete visual context for the topic.",
  };
  const cleanTitle = title.replace(/^File:\s*/i, "").slice(0, 100);
  return `${framing[category].replace(/\.$/, "")}: ${cleanTitle}.`.slice(0, 220);
}

function resultCount(userQuery: string, response: string, category: VisualCategory): number {
  const complex = /\b(compare|comparison|versus|vs\.?|differences|types|examples|structure|stages|process|history)\b/i.test(userQuery)
    || response.length > 2800;
  const scientific = ["mathematics", "physics", "astronomy", "biology", "chemistry", "engineering"].includes(category);
  if (complex && scientific) return 5;
  if (complex || scientific) return 3;
  return 1;
}

function cacheKey(query: string, count: number): string {
  return `${query.toLowerCase().replace(/\s+/g, " ").trim()}::${count}`;
}

function relevanceScore(title: string, description: string, userQuery: string, category: VisualCategory): number {
  const haystack = `${title} ${description}`.toLowerCase();
  const queryText = userQuery.toLowerCase();
  const requiredTerms =
    /\b(dna|deoxyribonucleic acid)\b/.test(queryText)
      ? ["dna", "double helix", "deoxyribonucleic"]
      : /\bquantum field theor(?:y|ies)\b/.test(queryText)
        ? ["quantum", "feynman", "field theory", "particle"]
        : /\bblack holes?\b/.test(queryText)
          ? ["black hole", "event horizon", "accretion", "singularity"]
          : [];
  if (requiredTerms.length > 0 && !requiredTerms.some(term => haystack.includes(term))) return 0;
  const tokens = userQuery
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, " ")
    .split(/\s+/)
    .filter(token => token.length > 2 && !["scientific", "visualization", "diagram", "reference", "structure", "molecular"].includes(token))
    .slice(0, 8);
  const matches = tokens.filter(token => haystack.includes(token)).length;
  const categoryTerms: Record<VisualCategory, string[]> = {
    science: ["science", "scientific"],
    mathematics: ["math", "mathemat", "geometry"],
    physics: ["physics", "quantum", "particle", "photon", "electron"],
    astronomy: ["astronomy", "space", "star", "galaxy", "planet"],
    biology: ["biology", "cell", "dna", "gene", "anatom"],
    chemistry: ["chemistry", "molecule", "chemical", "atom"],
    geography: ["map", "geography", "mountain", "river"],
    architecture: ["architecture", "building", "structure"],
    engineering: ["engineering", "machine", "technical", "bridge"],
    people: ["portrait", "person", "photograph"],
    places: ["place", "city", "landmark"],
    history: ["history", "historical", "artifact"],
    animals: ["animal", "species", "natural history"],
    plants: ["plant", "botanical", "flower", "tree"],
    hardware: ["hardware", "computer", "circuit", "device"],
    technology: ["technology", "computer", "robot", "technical"],
    concept: ["diagram", "visualization", "illustration"],
    other: [],
  };
  const categoryMatch = categoryTerms[category].some(term => haystack.includes(term));
  if (matches === 0) return 0;
  return Math.min(100, 68 + matches * 10 + (categoryMatch ? 12 : 0));
}

async function searchWikimedia(query: string, count: number, category: VisualCategory, userQuery: string): Promise<VisualReference[]> {
  const url = new URL("https://commons.wikimedia.org/w/api.php");
  url.searchParams.set("action", "query");
  url.searchParams.set("generator", "search");
  url.searchParams.set("gsrsearch", query);
  url.searchParams.set("gsrnamespace", "6");
  url.searchParams.set("gsrlimit", String(Math.min(count * 2, 8)));
  url.searchParams.set("prop", "imageinfo");
  url.searchParams.set("iiprop", "url|mime|size|extmetadata");
  url.searchParams.set("iiurlwidth", "1400");
  url.searchParams.set("format", "json");
  url.searchParams.set("origin", "*");

  const response = await fetch(url, {
    headers: { Accept: "application/json", "User-Agent": "Cosmos-Singularity/1.0 visual references" },
    signal: AbortSignal.timeout(7_000),
  });
  if (!response.ok) throw new Error(`Wikimedia Commons returned ${response.status}`);

  const payload = await response.json() as {
    query?: {
      pages?: Record<string, {
        pageid?: number;
        title?: string;
        canonicalurl?: string;
        imageinfo?: Array<{
          url?: string;
          thumburl?: string;
          mime?: string;
          width?: number;
          height?: number;
          extmetadata?: {
            ImageDescription?: { value?: string };
            Categories?: { value?: string };
          };
        }>;
      }>;
    };
  };

  const seen = new Set<string>();
  return Object.values(payload.query?.pages ?? [])
    .flatMap(page => {
      const info = page.imageinfo?.[0];
      const imageUrl = info?.thumburl ?? info?.url;
      const title = page.title ?? "";
      const description = info?.extmetadata?.ImageDescription?.value ?? "";
      const confidence = relevanceScore(title, description, `${userQuery} ${query}`, category);
      if (
        !page.pageid ||
        !title ||
        !imageUrl ||
        !info?.mime?.startsWith("image/") ||
        (info.width ?? 0) < 640 ||
        (info.height ?? 0) < 400 ||
        confidence < 80 ||
        REJECT_IMAGE_PATTERN.test(`${title} ${description} ${info.extmetadata?.Categories?.value ?? ""}`) ||
        seen.has(imageUrl)
      ) return [];
      seen.add(imageUrl);
      const cleanTitle = title.replace(/^File:\s*/i, "").replace(/_/g, " ");
      const reference: VisualReference = {
        id: `wikimedia-${page.pageid}`,
        title: cleanTitle.slice(0, 140),
        caption: captionFor(query, cleanTitle, category),
        imageUrl,
        sourceUrl: page.canonicalurl ?? `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, "_"))}`,
        source: "Wikimedia Commons",
        alt: `${cleanTitle.slice(0, 160)} — visual reference for ${userQuery.slice(0, 90)}`,
        confidence,
        sourceTier: 2,
        width: info.width ?? 0,
        height: info.height ?? 0,
      };
      return [reference];
    })
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, count);
}

function fallbackQueryFor(category: VisualCategory): string | null {
  const fallbacks: Partial<Record<VisualCategory, string>> = {
    science: "scientific diagram visualization",
    mathematics: "mathematical diagram visualization",
    physics: "physics scientific diagram",
    astronomy: "astronomy scientific visualization",
    biology: "biology scientific illustration",
    chemistry: "chemistry molecular diagram",
    geography: "geographic map reference",
    architecture: "architectural reference photograph",
    engineering: "engineering technical diagram",
    people: "historical portrait photograph",
    places: "landmark reference photograph",
    history: "historical artifact photograph",
    animals: "natural history scientific illustration",
    plants: "botanical scientific photograph",
    hardware: "hardware technical photograph",
    technology: "engineering technical diagram",
  };
  return fallbacks[category] ?? null;
}

router.post("/visual-references", async (req, res) => {
  const userQuery = typeof req.body?.query === "string" ? req.body.query.trim().slice(0, 500) : "";
  const responseText = typeof req.body?.response === "string" ? req.body.response.trim().slice(0, 4_000) : "";
  if (!userQuery || !responseText) {
    res.json({ enabled: false, references: [] });
    return;
  }

  const decision = classifyVisualNeed(userQuery, responseText);
  if (!decision.enabled) {
    res.json({ enabled: false, references: [], category: decision.category });
    return;
  }

  const query = buildEducationalQuery(userQuery, responseText, decision.category);
  const count = resultCount(userQuery, responseText, decision.category);
  const key = cacheKey(query, count);
  const cached = visualReferenceCache.get(key);
  if (cached && cached.expiresAt > Date.now()) {
    res.json({
      enabled: cached.references.length > 0,
      references: cached.references,
      query,
      category: decision.category,
      confidence: decision.confidence,
    });
    return;
  }

  try {
    let references = await searchWikimedia(query, count, decision.category, userQuery);
    if (references.length === 0) {
      const fallbackQuery = fallbackQueryFor(decision.category);
      if (fallbackQuery && fallbackQuery !== query) {
        references = await searchWikimedia(fallbackQuery, count, decision.category, userQuery);
      }
    }
    visualReferenceCache.set(key, { expiresAt: Date.now() + VISUAL_REFERENCE_CACHE_TTL_MS, references });
    if (visualReferenceCache.size > 250) {
      for (const [cacheEntryKey, entry] of visualReferenceCache) {
        if (entry.expiresAt <= Date.now()) visualReferenceCache.delete(cacheEntryKey);
      }
    }
    res.json({
      enabled: references.length > 0,
      references,
      query,
      category: decision.category,
      confidence: decision.confidence,
    });
  } catch (error) {
    console.warn("[visual-references] search unavailable", error);
    res.json({
      enabled: false,
      references: [],
      query,
      category: decision.category,
      confidence: decision.confidence,
    });
  }
});

export default router;